### PR TITLE
SpookVooper API 2.0 PR

### LINKED ISSUE #6: Get groups done
- [x] Add all routes
- [x] Test

### LINKED ISSUE #7: Get Auth Done
- [x] Get all routes completed
- [x] Add typings
- [x] Test

### LINKED ISSUE #14: Stocks
# Stock
Add stock support into SVAPI 2.0

## Todo
- [x] Add `getValue()`
- [x] Add `getStockBuyPrice()`
- [x] Add `getQueueInfo()`
- [x] Add `getOwner()`
- [x] Add getters and setters

### LINKED ISSUE #16: ExchangeHub
# ExchangeHub Issue
We need to get ExchangeHub done

## To-do List
 - [x] Copy boilerplate code from [TransactionHub](https://github.com/vexico/spookvooper-api/blob/development/src/modules/TransactionHub.ts)
 - [x] Add `StockOffer` listener
 - [x] Add `StockOfferCancel` listener
 - [x] Add `StockTrade` listener
 - [x] Add `RecieveMessage` listener
 - [x] Add `RecieveMessageHistory` listener
 - [x] Configure system to send commands to ExchangeHub
 - [x] Add required types and interfaces

## Metadata (as of writing)
**Labels**: Enhancement, Doing
**Assignee**: @brndnln 
**Project**: [Development Board](https://github.com/vexico/spookvooper-api/projects/1)
**Milestone**: [TS Rewrite](https://github.com/vexico/spookvooper-api/milestone/1)
**Linked Pull Request**: #13

### LINKED ISSUE #18: Add depersonalized data fetching + More

### PR DESCRIPTION
**Pull request by identithree**
# SVAPI 2.0 PR
A Pull request for the new 2.0 launch

## Changes Made (as of writing)
- 💻 New sync
- ➕ Add Groups to SVAPI
- Add files via upload
- 💻 Sync with laptop
- ➕ Add Auth to SVAPI
- 💻 Sync with local
- 💻 Sync with local
- 💻 Sync with local
- 💻 TransactionHub almost done (Sync with local)

### CODE REVIEW

**Comment by identithree** [comment]
Issue created for stocks: #14

**Comment by identithree** [comment]
Stocks are now completed. On to ExchangeHub

**Comment by identithree** [comment]
Groups are now officially allowed to buy and sell stock. Payment is now fixed.

This needs to be committed, however I am not home and the changes are on my local machine.

**Comment by identithree** [comment]
Holy moly, changes coming soon. Apologies, I am out of school however am out and about with my mother

**Review by identithree — COMMENTED** [review]
Looks good, should be good to merge.

**Review by pinktanuki — APPROVED** [review]
Did not see any major errors

**Pull request merged**
